### ISSUE TITLE
Looks good! Some suggestions

### ISSUE THREAD

**Issue by eddiejaoude** [vj-abishek/invite-on-issue#1]
Just had a quick look, looks good, some of my initial thoughts...

- do not use `if` in workflow, have this as part of `index.js` to avoid user error
- `if (label === "bug") // or invite me to the organisation` have this as a parameter to pass from the workflow
- `const org = "EddieJaoudeCommunity"` also have this passed from the workflow

**Comment by vj-abishek** [comment]
Will fix it soon

**Comment by vj-abishek** [comment]
Sorry accidentially closed it

**Comment by vj-abishek** [comment]
Fixed those. Now review it
