### ISSUE TITLE
Node Modules folder

### ISSUE THREAD

**Issue by dumbcoder7** [vj-abishek/invite-on-issue#3]
Consider adding the `node_modules` folder to a `.gitignore` file.

**Comment by vj-abishek** [comment]
Yes node_modules folder shouldn't be in GitHub . But in their [docs](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github) they are saying to add the node modules

> If you added a .gitignore file that lists node_modules, you'll need to remove that line to commit the node_modules directory.

**Comment by vj-abishek** [comment]
But there is also this option

> Checking in your node_modules directory can cause problems. As an alternative, you can use a tool called @vercel/ncc to compile your code and modules into one file used for distribution.

**Comment by vj-abishek** [comment]
I think I will use @vercel/ncc package instead of node_modules
