### ISSUE TITLE
DOCS: Update example in README and make documentation for setup

### ISSUE THREAD

**Issue by Vyvy-vi** [vj-abishek/invite-on-issue#5]
THe current example code in the README looks outdated.
A newer one would be more helpful. I'm seeing a significant amount of people wanting to use this :D

**Comment by vj-abishek** [comment]
@Vyvy-vi This repo is not the correct repo. https://github.com/vj-abigo/invite-on-label this is the correct repo

I'm sorry I will delete this repo.

**Comment by vj-abishek** [comment]
Is the documentation available in https://github.com/vj-abigo/invite-on-label is enough?

**Comment by Vyvy-vi** [comment]
Yes, it is :+1:

**Comment by vj-abishek** [comment]
Could you make those changes in that repo?
